set_property -dict { PACKAGE_PIN K17 IOSTANDARD LVCMOS33 } [get_ports { sys_clock }]
create_clock -add -name sys_clk_pin -period 8.00 -waveform {0 4} [get_ports { sys_clock }]

set_property IOSTANDARD LVCMOS33 [get_ports led_0_rx_0]
set_property IOSTANDARD LVCMOS33 [get_ports led_1_rx_0]
set_property IOSTANDARD LVCMOS33 [get_ports i_rx_0]
set_property IOSTANDARD LVCMOS33 [get_ports led_2_tx_0]
set_property IOSTANDARD LVCMOS33 [get_ports led_3_tx_0]
set_property IOSTANDARD LVCMOS33 [get_ports TX_0]
set_property PACKAGE_PIN M14 [get_ports led_0_rx_0]
set_property PACKAGE_PIN M15 [get_ports led_1_rx_0]
set_property PACKAGE_PIN G14 [get_ports led_2_tx_0]
set_property PACKAGE_PIN D18 [get_ports led_3_tx_0]
set_property PACKAGE_PIN V15 [get_ports i_rx_0]
set_property PACKAGE_PIN W15 [get_ports TX_0]
